language: node_js
node_js:
  - "stable"
branches:
except:
  - master
cache:
directories:
  - "node_modules"
before_install:
  - npm update
after_success:
  - bash <(curl -s https://codecov.io/bash)
script:
  - cd client && npm run test:unit-coverage && npm run test:e2e-coverage && npm run upload-coverage
