language: node_js
node_js:
  - "stable"
addons:
  chrome: stable
  hosts:
    - localhost
branches:
except:
  - master
cache:
  npm: true
directories:
  - ./node_modules
  - ./client/node_modules
  - ./server/node_modules
  - ~/.cache
override:
  - npm ci
  - npm run cypress verify
before_install:
  - cd server && npm update && cd ../client && npm update
install:
  - cd ../server && npm i && cd ../client && npm i 
script:
  - npm run test:unit
  - start-server-and-test local:server http://localhost:9000 local:client http://localhost:3000 'npm run test:e2e-headless'
  - npm run collate-coverage
  - kill $(jobs -p) || true
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/final-report/coverage-final.json -t token -v
